# Generated by Django 5.2.15 on 2026-06-17 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CMSPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text="The unique slug URL path (e.g., 'home-page', 'bistro-menu')", unique=True)),
                ('description', models.TextField(blank=True, help_text='SEO page excerpt metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CMS Page',
                'verbose_name_plural': 'CMS Pages',
            },
        ),
        migrations.CreateModel(
            name='DynamicPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text="The URL path ending (e.g. 'about-us')", unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My Custom Layout', max_length=255)),
                ('is_published', models.BooleanField(default=False)),
                ('sections', models.JSONField(help_text='Nested JSON array containing section columns, layouts, padding, and custom inner page elements.')),
                ('theme', models.JSONField(help_text='Hex color theme specifications, font-family parameters, and custom brand visual states.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PageButtonAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Contact Us', help_text='Text content written inside the button', max_length=100)),
                ('destination_url', models.CharField(default='#', help_text='Anchored navigation page or external URL link', max_length=255)),
                ('bg_color', models.CharField(default='#4F46E5', help_text='Hex code of the button background', max_length=30)),
                ('text_color', models.CharField(default='#FFFFFF', max_length=30)),
                ('font_size', models.CharField(default='14px', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Ascending render sequence index')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='button_blocks', to='cms_app.cmspage')),
            ],
            options={
                'verbose_name': 'Page Button Block',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='PageFieldBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('text', 'Rich Text Section / Header'), ('button', 'Call to Action Button'), ('image', 'Interactive Image Banner'), ('divider', 'Horizontal Line Divider'), ('spacer', 'Vertical Spacing block')], default='text', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Sequence order of the block on the page')),
                ('data', models.JSONField(default=dict, help_text="Custom key-value configurations (e.g. {'content': 'Hello World', 'font_size': '24px'})")),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='cms_app.dynamicpage')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='PageImageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(help_text='URL direct source of the graphic', max_length=500)),
                ('alt_text', models.CharField(blank=True, help_text='Accessibility alt banner tag', max_length=255)),
                ('border_radius', models.CharField(default='8px', help_text="Corner curves (e.g., '12px', '0px')", max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Ascending render sequence index')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_blocks', to='cms_app.cmspage')),
            ],
            options={
                'verbose_name': 'Page Image Block',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='PageTextBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='The rich text content body')),
                ('font_size', models.CharField(default='16px', help_text="Typography size (e.g., '32px', '14px')", max_length=20)),
                ('font_weight', models.CharField(default='400', help_text="Font weight weight (e.g., '700', '400')", max_length=10)),
                ('text_align', models.CharField(default='left', help_text='Alignment options (left/center/right)', max_length=15)),
                ('color', models.CharField(default='#0F172A', help_text='CSS hex color code', max_length=30)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Ascending render sequence index')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_blocks', to='cms_app.cmspage')),
            ],
            options={
                'verbose_name': 'Page Text Block',
                'ordering': ['sort_order'],
            },
        ),
    ]
